name: Terraform Workflow

on:
  push:
    branches:
      - main
  

jobs:
  terraform:
    runs-on: self-hosted  # Runs on your self-hosted runner instead of GitHub-hosted ones
    env:
      MY_ACCESS_KEY: ${{ secrets.MY_ACCESS_KEY }}
      MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY}}
      AWS_DEFAULT_REGION: ap-south-1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip
    

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
